In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Mitsamiouli,KM,2022-07-21 22:47:46,-11.3847,43.2844,75.02,72,6,5.59
1,1,Airai,TL,2022-07-21 22:45:45,-8.9266,125.4092,57.38,85,98,3.78
2,2,Puerto Escondido,MX,2022-07-21 22:44:47,15.8500,-97.0667,84.52,76,99,3.27
3,3,Kapaa,US,2022-07-21 22:44:28,22.0752,-159.3190,84.52,68,40,16.11
4,4,Rikitea,PF,2022-07-21 22:44:28,-23.1203,-134.9692,74.10,80,94,23.02

In [3]:
#get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [6]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [10]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
#center of earth is 30 degrees N and 31 degrees E
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, 
                                weights=[max(temp, 0) for temp in max_temp], 
                                dissipating=False, 
                                max_intensity=300,
                                point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, 
                                 weights=humidity, 
                                 dissipating=False, 
                                 max_intensity=300, 
                                 point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, 
                                 weights=clouds, 
                                 dissipating=False, 
                                 max_intensity=300, 
                                 point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, 
                                 weights=wind, 
                                 dissipating=False, 
                                 max_intensity=300, 
                                 point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [16]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & 
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Mitsamiouli,KM,2022-07-21 22:47:46,-11.3847,43.2844,75.02,72,6,5.59
2,2,Puerto Escondido,MX,2022-07-21 22:44:47,15.8500,-97.0667,84.52,76,99,3.27
3,3,Kapaa,US,2022-07-21 22:44:28,22.0752,-159.3190,84.52,68,40,16.11
8,8,Butaritari,KI,2022-07-21 22:44:39,3.0707,172.7902,81.48,73,57,5.41
9,9,Cayenne,GF,2022-07-21 22:47:47,4.9333,-52.3333,83.08,1,20,3.44
10,10,Gat,IL,2022-07-21 22:47:48,31.6100,34.7642,77.68,100,2,2.39
15,15,Crossville,US,2022-07-21 22:47:13,35.9490,-85.0269,81.45,88,75,0.00
17,17,Puerto Ayora,EC,2022-07-21 22:47:50,-0.7393,-90.3518,78.76,94,53,5.01
19,19,Murgab,TM,2022-07-21 22:47:51,37.4966,61.9714,84.07,32,0,4.61
20,20,Lorengau,PG,2022-07-21 22:44:36,-2.0226,147.2712,83.59,74,87,10.16

In [17]:
preferred_cities_df.count()

City_ID       190
City          190
Country       190
Date          190
Lat           190
Lng           190
Max Temp      190
Humidity      190
Cloudiness    190
Wind Speed    190
dtype: int64

In [18]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                City Country  Max Temp      Lat       Lng Hotel Name
0        Mitsamiouli      KM     75.02 -11.3847   43.2844
2   Puerto Escondido      MX     84.52  15.8500  -97.0667
3              Kapaa      US     84.52  22.0752 -159.3190
8         Butaritari      KI     81.48   3.0707  172.7902
9            Cayenne      GF     83.08   4.9333  -52.3333
10               Gat      IL     77.68  31.6100   34.7642
15        Crossville      US     81.45  35.9490  -85.0269
17      Puerto Ayora      EC     78.76  -0.7393  -90.3518
19            Murgab      TM     84.07  37.4966   61.9714
20          Lorengau      PG     83.59  -2.0226  147.2712

In [34]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [35]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"(lat),(lng)"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.